version: "3"
services:
  proxy:
    image: library/nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html/index.html:/etc/nginx/html/index.html:ro
      - ./html/Logo-Exxcellent-RGB-300.png:/etc/nginx/html/Logo-Exxcellent-RGB-300.png:ro
      - ./html/style.css:/etc/nginx/html/style.css:ro
    container_name: proxy
    hostname: proxy
    command: nginx -g "daemon off;"
  fundamentals:
    image: docker-registry.paul-blaesi.de/fundamentals:latest
    container_name: fundamentals
    hostname: fundamentals
  ui5:
    image: docker-registry.paul-blaesi.de/ui5:latest
    container_name: ui5
    hostname: ui5
  webcomponents:
    image: docker-registry.paul-blaesi.de/webcomponents:latest
    container_name: webcomponents
    hostname: webcomponents
