version: "3"
services:
  proxy:
    image: library/nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: proxy
    hostname: proxy
    command: nginx -g "daemon off;"
  fundamentals:
    build:
      context: ../fundmentals-lib-react-sample-app
      dockerfile: Dockerfile
    container_name: fundamentals
    hostname: fundamentals
  ui5:
    build:
      context: ../sapui5-sample-app
      dockerfile: Dockerfile
    container_name: ui5
    hostname: ui5
  webcomponents:
    build:
      context: ../ui5-webcomponents-for-react-sample-app
      dockerfile: Dockerfile
    container_name: webcomponents
    hostname: webcomponents
